### imports

In [1]:
import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

For this part, you need to change dir_path to path of ypur directory which contains .csv files.

In [2]:
dir_path = "/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset"

In [3]:
files, x, y, z = [],[], [], []

In [4]:
for file in os.listdir(dir_path):
    if file.endswith(".txt"):
        files.append(os.path.join(dir_path, file))

In [5]:
files = sorted(files)
files

['/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_1.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_10.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_11.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_12.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_13.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_14.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_15.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_16.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_17.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_18.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_19.txt',
 '/Users/ecem/Documents/GitHub/seismocardiogram/data/healty-dataset/sub_2.txt',
 '/Users/ecem/Documents/GitHub

In [8]:
pd.read_csv(files[0],header =  None, delimiter =' ')

0     1      2      3      4     5     6   7
0      -436  6080  16892  -1704      0     0     0 NaN
1       446  -712  -1160 -16448   1024  1536  -256 NaN
2      -553  -688  -1056 -16432   1024  1792     0 NaN
3      -726  -736  -1072 -16408   2048  2048  -257 NaN
4       236  -712  -1112 -16408   1024  2048  -513 NaN
...     ...   ...    ...    ...    ...   ...   ...  ..
146683  819  -344  -1392 -16328  20736 -9729  9728 NaN
146684  509  -320  -1456 -16248  20736 -8705  9728 NaN
146685 -824  -312  -1400 -16312  19712 -7681  8704 NaN
146686  807  -344  -1416 -16320  19456 -7681  9728 NaN
146687  542  -368  -1432 -16352  19712 -5377  9472 NaN

[146688 rows x 8 columns]

In [10]:
pd.read_csv(files[0],header =  None, delimiter =' ').iloc[0:,1]

0         6080
1         -712
2         -688
3         -736
4         -712
          ... 
146683    -344
146684    -320
146685    -312
146686    -344
146687    -368
Name: 1, Length: 146688, dtype: int64

In [12]:
pd.read_csv(files[0],header =  None, delimiter =' ').iloc[0:,2]

0         16892
1         -1160
2         -1056
3         -1072
4         -1112
          ...  
146683    -1392
146684    -1456
146685    -1400
146686    -1416
146687    -1432
Name: 2, Length: 146688, dtype: int64

In [13]:
pd.read_csv(files[0],header =  None, delimiter =' ').iloc[0:,2]

0         16892
1         -1160
2         -1056
3         -1072
4         -1112
          ...  
146683    -1392
146684    -1456
146685    -1400
146686    -1416
146687    -1432
Name: 2, Length: 146688, dtype: int64

In [11]:
for i in range(len(files)):
    t = pd.read_csv(files[i],header =  None, delimiter =' ')
    
    x.append((np.array(t.iloc[0:,1].astype(float))))
    y.append(np.array(t.iloc[0:,2].astype(float)))
    z.append(np.array(t.iloc[0:,3].astype(float)))

In [7]:
type(x[0][0])

numpy.float64

In [8]:
print(len(x))
print(len(y))
print(len(z))

29
29
29


In [9]:
x[0]

array([6080., -712., -688., ..., -320., -312., -344.])

In [10]:
y[0]

array([16892., -1160., -1056., ..., -1456., -1400., -1416.])

In [11]:
z[0]

array([ -1704., -16448., -16432., ..., -16248., -16312., -16320.])

In [12]:
np.save(dir_path + "/SCG_x", x, allow_pickle= True)
np.save(dir_path + "/SCG_y", y, allow_pickle= True)
np.save(dir_path + "/SCG_z", z, allow_pickle= True)

x = np.load(dir_path + "/SCG_x.npy", allow_pickle= True)

In [13]:
x[0].shape

(146687,)